package com.bearwaves.eos4j;

public enum EOSResultCode {

    SUCCESS(0),

    NO_CONNECTION(1),
    INVALID_CREDENTIALS(2),
    INVALID_USER(3),
    INVALID_AUTH(4),
    ACCESS_DENIED(5),
    MISSING_PERMISSIONS(6),
    TOKEN_NOT_ACCOUNT(7),
    TOO_MANY_REQUESTS(8),
    ALREADY_PENDING(9),
    INVALID_PARAMETERS(10),
    INVALID_REQUEST(11),
    UNRECOGNIZED_RESPONSE(12),
    INCOMPATIBLE_VERSION(13),
    NOT_CONFIGURED(14),
    ALREADY_CONFIGURED(15),
    NOT_IMPLEMENTED(16),
    CANCELED(17),
    NOT_FOUND(18),
    OPERATION_WILL_RETRY(19),
    NO_CHANGE(20),
    VERSION_MISMATCH(21),
    LIMIT_EXCEEDED(22),
    DISABLED(23),
    DUPLICATE_NOT_ALLOWED(24),
    MISSING_PARAMETERS_DEPRECATED(25),
    INVALID_SANDBOX_ID(26),
    TIMED_OUT(27),
    PARTIAL_RESULT(28),
    MISSING_ROLE(29),
    MISSING_FEATURE(30),
    INVALID_SANDBOX(31),
    INVALID_DEPLOYMENT(32),
    INVALID_PRODUCT(33),
    INVALID_PRODUCT_USER_ID(34),
    SERVICE_FAILURE(35),
    CACHE_DIRECTORY_MISSING(36),
    CACHE_DIRECTORY_INVALID(37),
    INVALID_STATE(38),
    REQUEST_IN_PROGRESS(39),
    APPLICATION_SUSPENDED(40),
    NETWORK_DISCONNECTED(41),

    AUTH_ACCOUNT_LOCKED(1001),
    AUTH_ACCOUNT_LOCKED_FOR_UPDATE(1002),
    AUTH_INVALID_REFRESH_TOKEN(1003),
    AUTH_INVALID_TOKEN(1004),
    AUTH_AUTHENTICATION_FAILURE(1005),
    AUTH_INVALID_PLATFORM_TOKEN(1006),
    AUTH_WRONG_ACCOUNT(1007),
    AUTH_WRONG_CLIENT(1008),
    AUTH_FULL_ACCOUNT_REQUIRED(1009),
    AUTH_HEADLESS_ACCOUNT_REQUIRED(1010),
    AUTH_PASSWORD_RESET_REQUIRED(1011),
    AUTH_PASSWORD_CANNOT_BE_REUSED(1012),
    AUTH_EXPIRED(1013),
    AUTH_SCOPE_CONSENT_REQUIRED(1014),
    AUTH_APPLICATION_NOT_FOUND(1015),
    AUTH_SCOPE_NOT_FOUND(1016),
    AUTH_ACCOUNT_FEATURE_RESTRICTED(1017),
    AUTH_ACCOUNT_PORTAL_LOAD_ERROR(1018),
    AUTH_CORRECTIVE_ACTION_REQUIRED(1019),

    AUTH_PIN_GRANT_CODE(1020),
    AUTH_PIN_GRANT_EXPIRED(1021),
    AUTH_PIN_GRANT_PENDING(1022),

    AUTH_EXTERNAL_AUTH_NOT_LINKED(1030),
    AUTH_EXTERNAL_AUTH_REVOKED(1032),
    AUTH_EXTERNAL_AUTH_INVALID(1033),
    AUTH_EXTERNAL_AUTH_RESTRICTED(1034),
    AUTH_EXTERNAL_AUTH_CANNOT_LOGIN(1035),
    AUTH_EXTERNAL_AUTH_EXPIRED(1036),
    AUTH_EXTERNAL_AUTH_IS_LAST_LOGIN_TYPE(1037),

    AUTH_EXCHANGE_CODE_NOT_FOUND(1040),
    AUTH_ORIGINATING_EXCHANGE_CODE_SESSION_EXPIRED(1041),

    AUTH_ACCOUNT_NOT_ACTIVE(1050),

    AUTH_MFAREQUIRED(1060),

    AUTH_PARENTAL_CONTROLS(1070),

    AUTH_NO_REAL_ID(1080),

    FRIENDS_INVITE_AWAITING_ACCEPTANCE(2000),
    FRIENDS_NO_INVITATION(2001),
    FRIENDS_ALREADY_FRIENDS(2003),
    FRIENDS_NOT_FRIENDS(2004),
    FRIENDS_TARGET_USER_TOO_MANY_INVITES(2005),
    FRIENDS_LOCAL_USER_TOO_MANY_INVITES(2006),
    FRIENDS_TARGET_USER_FRIEND_LIMIT_EXCEEDED(2007),
    FRIENDS_LOCAL_USER_FRIEND_LIMIT_EXCEEDED(2008),

    PRESENCE_DATA_INVALID(3000),
    PRESENCE_DATA_LENGTH_INVALID(3001),
    PRESENCE_DATA_KEY_INVALID(3002),
    PRESENCE_DATA_KEY_LENGTH_INVALID(3003),
    PRESENCE_DATA_VALUE_INVALID(3004),
    PRESENCE_DATA_VALUE_LENGTH_INVALID(3005),
    PRESENCE_RICH_TEXT_INVALID(3006),
    PRESENCE_RICH_TEXT_LENGTH_INVALID(3007),
    PRESENCE_STATUS_INVALID(3008),

    ECOM_ENTITLEMENT_STALE(4000),
    ECOM_CATALOG_OFFER_STALE(4001),
    ECOM_CATALOG_ITEM_STALE(4002),
    ECOM_CATALOG_OFFER_PRICE_INVALID(4003),
    ECOM_CHECKOUT_LOAD_ERROR(4004),

    SESSIONS_SESSION_IN_PROGRESS(5000),
    SESSIONS_TOO_MANY_PLAYERS(5001),
    SESSIONS_NO_PERMISSION(5002),
    SESSIONS_SESSION_ALREADY_EXISTS(5003),
    SESSIONS_INVALID_LOCK(5004),
    SESSIONS_INVALID_SESSION(5005),
    SESSIONS_SANDBOX_NOT_ALLOWED(5006),
    SESSIONS_INVITE_FAILED(5007),
    SESSIONS_INVITE_NOT_FOUND(5008),
    SESSIONS_UPSERT_NOT_ALLOWED(5009),
    SESSIONS_AGGREGATION_FAILED(5010),
    SESSIONS_HOST_AT_CAPACITY(5011),
    SESSIONS_SANDBOX_AT_CAPACITY(5012),
    SESSIONS_SESSION_NOT_ANONYMOUS(5013),
    SESSIONS_OUT_OF_SYNC(5014),
    SESSIONS_TOO_MANY_INVITES(5015),
    SESSIONS_PRESENCE_SESSION_EXISTS(5016),
    SESSIONS_DEPLOYMENT_AT_CAPACITY(5017),
    SESSIONS_NOT_ALLOWED(5018),
    SESSIONS_PLAYER_SANCTIONED(5019),

    PLAYER_DATA_STORAGE_FILENAME_INVALID(6000),
    PLAYER_DATA_STORAGE_FILENAME_LENGTH_INVALID(6001),
    PLAYER_DATA_STORAGE_FILENAME_INVALID_CHARS(6002),
    PLAYER_DATA_STORAGE_FILE_SIZE_TOO_LARGE(6003),
    PLAYER_DATA_STORAGE_FILE_SIZE_INVALID(6004),
    PLAYER_DATA_STORAGE_FILE_HANDLE_INVALID(6005),
    PLAYER_DATA_STORAGE_DATA_INVALID(6006),
    PLAYER_DATA_STORAGE_DATA_LENGTH_INVALID(6007),
    PLAYER_DATA_STORAGE_START_INDEX_INVALID(6008),
    PLAYER_DATA_STORAGE_REQUEST_IN_PROGRESS(6009),
    PLAYER_DATA_STORAGE_USER_THROTTLED(6010),
    PLAYER_DATA_STORAGE_ENCRYPTION_KEY_NOT_SET(6011),
    PLAYER_DATA_STORAGE_USER_ERROR_FROM_DATA_CALLBACK(6012),
    PLAYER_DATA_STORAGE_FILE_HEADER_HAS_NEWER_VERSION(6013),
    PLAYER_DATA_STORAGE_FILE_CORRUPTED(6014),

    CONNECT_EXTERNAL_TOKEN_VALIDATION_FAILED(7000),
    CONNECT_USER_ALREADY_EXISTS(7001),
    CONNECT_AUTH_EXPIRED(7002),
    CONNECT_INVALID_TOKEN(7003),
    CONNECT_UNSUPPORTED_TOKEN_TYPE(7004),
    CONNECT_LINK_ACCOUNT_FAILED(7005),
    CONNECT_EXTERNAL_SERVICE_UNAVAILABLE(7006),
    CONNECT_EXTERNAL_SERVICE_CONFIGURATION_FAILURE(7007),
    CONNECT_LINK_ACCOUNT_FAILED_MISSING_NINTENDO_ID_ACCOUNT_DEPRECATED(7008),

    UI_SOCIAL_OVERLAY_LOAD_ERROR(8000),

    LOBBY_NOT_OWNER(9000),
    LOBBY_INVALID_LOCK(9001),
    LOBBY_LOBBY_ALREADY_EXISTS(9002),
    LOBBY_SESSION_IN_PROGRESS(9003),
    LOBBY_TOO_MANY_PLAYERS(9004),
    LOBBY_NO_PERMISSION(9005),
    LOBBY_INVALID_SESSION(9006),
    LOBBY_SANDBOX_NOT_ALLOWED(9007),
    LOBBY_INVITE_FAILED(9008),
    LOBBY_INVITE_NOT_FOUND(9009),
    LOBBY_UPSERT_NOT_ALLOWED(9010),
    LOBBY_AGGREGATION_FAILED(9011),
    LOBBY_HOST_AT_CAPACITY(9012),
    LOBBY_SANDBOX_AT_CAPACITY(9013),
    LOBBY_TOO_MANY_INVITES(9014),
    LOBBY_DEPLOYMENT_AT_CAPACITY(9015),
    LOBBY_NOT_ALLOWED(9016),
    LOBBY_MEMBER_UPDATE_ONLY(9017),
    LOBBY_PRESENCE_LOBBY_EXISTS(9018),
    LOBBY_VOICE_NOT_ENABLED(9019),

    TITLE_STORAGE_USER_ERROR_FROM_DATA_CALLBACK(10000),
    TITLE_STORAGE_ENCRYPTION_KEY_NOT_SET(10001),
    TITLE_STORAGE_FILE_CORRUPTED(10002),
    TITLE_STORAGE_FILE_HEADER_HAS_NEWER_VERSION(10003),

    MODS_MOD_SDK_PROCESS_IS_ALREADY_RUNNING(11000),
    MODS_MOD_SDK_COMMAND_IS_EMPTY(11001),
    MODS_MOD_SDK_PROCESS_CREATION_FAILED(11002),
    MODS_CRITICAL_ERROR(11003),
    MODS_TOOL_INTERNAL_ERROR(11004),
    MODS_IPC_FAILURE(11005),
    MODS_INVALID_IPC_RESPONSE(11006),
    MODS_URI_LAUNCH_FAILURE(11007),
    MODS_MOD_IS_NOT_INSTALLED(11008),
    MODS_USER_DOES_NOT_OWN_THE_GAME(11009),
    MODS_OFFER_REQUEST_BY_ID_INVALID_RESULT(11010),
    MODS_COULD_NOT_FIND_OFFER(11011),
    MODS_OFFER_REQUEST_BY_ID_FAILURE(11012),
    MODS_PURCHASE_FAILURE(11013),
    MODS_INVALID_GAME_INSTALL_INFO(11014),
    MODS_CANNOT_GET_MANIFEST_LOCATION(11015),
    MODS_UNSUPPORTED_OS(11016),

    ANTI_CHEAT_CLIENT_PROTECTION_NOT_AVAILABLE(12000),
    ANTI_CHEAT_INVALID_MODE(12001),
    ANTI_CHEAT_CLIENT_PRODUCT_ID_MISMATCH(12002),
    ANTI_CHEAT_CLIENT_SANDBOX_ID_MISMATCH(12003),
    ANTI_CHEAT_PROTECT_MESSAGE_SESSION_KEY_REQUIRED(12004),
    ANTI_CHEAT_PROTECT_MESSAGE_VALIDATION_FAILED(12005),
    ANTI_CHEAT_PROTECT_MESSAGE_INITIALIZATION_FAILED(12006),
    ANTI_CHEAT_PEER_ALREADY_REGISTERED(12007),
    ANTI_CHEAT_PEER_NOT_FOUND(12008),
    ANTI_CHEAT_PEER_NOT_PROTECTED(12009),
    ANTI_CHEAT_CLIENT_DEPLOYMENT_ID_MISMATCH(12010),
    ANTI_CHEAT_DEVICE_ID_AUTH_IS_NOT_SUPPORTED(12011),

    RTC_TOO_MANY_PARTICIPANTS(13000),
    RTC_ROOM_ALREADY_EXISTS(13001),
    RTC_USER_KICKED(13002),
    RTC_USER_BANNED(13003),
    RTC_ROOM_WAS_LEFT(13004),
    RTC_RECONNECTION_TIMEGATE_EXPIRED(13005),
    RTC_SHUTDOWN_INVOKED(13006),
    RTC_USER_IS_IN_BLOCKLIST(13007),

    PROGRESSION_SNAPSHOT_SNAPSHOT_ID_UNAVAILABLE(14000),

    KWS_PARENT_EMAIL_MISSING(15000),
    KWS_USER_GRADUATED(15001),

    ANDROID_JAVA_VM_NOT_STORED(17000),

    PERMISSION_REQUIRED_PATCH_AVAILABLE(18000),
    PERMISSION_REQUIRED_SYSTEM_UPDATE(18001),
    PERMISSION_AGE_RESTRICTION_FAILURE(18002),
    PERMISSION_ACCOUNT_TYPE_FAILURE(18003),
    PERMISSION_CHAT_RESTRICTION(18004),
    PERMISSION_UGC_RESTRICTION(18005),
    PERMISSION_ONLINE_PLAY_RESTRICTED(18006),

    DESKTOP_CROSSPLAY_APPLICATION_NOT_BOOTSTRAPPED(19000),
    DESKTOP_CROSSPLAY_SERVICE_NOT_INSTALLED(19001),
    DESKTOP_CROSSPLAY_SERVICE_START_FAILED(19002),
    DESKTOP_CROSSPLAY_SERVICE_NOT_RUNNING(19003),

    UNEXPECTED_ERROR(0X7FFFFFFF);

    private final int value;

    final static EOSResultCode[] values;

    static {
        values = EOSResultCode.values();
    }

    EOSResultCode(int value) {
        this.value = value;
    }

    public int getValue() {
        return this.value;
    }

    public static EOSResultCode fromInt(int i) {
        for (EOSResultCode value : values) {
            if (value.value == i) {
                return value;
            }
        }
        return null;
    }

}
